Validations for employee/branch models have been added
BC-MAY-21-ROR/kata-07-reloj-checador-k7-f22-t4 pull request #27
Opened 2022-03-31 19:01 UTC by brocha05

# Description
What did you implemented/Why did you implemented this:
 - I added validations for employees/branch models

 - Why?
 - We dont want employees or branches with empty fields, also, some data should not be repeated.

 # Testing
Just try to add a employee with a empty field or with an email that is been using in another employee.

2022-03-31 19:03 UTC, dannharo reviewed
add tests please

2022-04-01 03:46 UTC, YilKanda requested changes
Resolve conflicts in your branch.

2022-04-05 19:44 UTC, vyk2rr requested changes, later dismissed
Add unit test to Models branch and Employee

2022-04-06 20:27 UTC, brocha05 commented
@vyk2rr @YilKanda Could you check again this PR? Thank you

2022-04-06 20:54 UTC, juperameza approved these changes, later dismissed
LGTM! :) <3

2022-04-06 20:54 UTC, AlejandroCuriel approved these changes, later dismissed
LGTM :rocket:  :racehorse:

2022-04-06 20:54 UTC, AlejandroCuriel commented on spec/models/branch_spec.rb
> +
you don't need to have so many line breaks

2022-04-06 20:57 UTC, juperameza approved these changes
LGTM x2

2022-04-06 20:58 UTC, AlejandroCuriel approved these changes
LGTM :rocket: :racehorse:

2022-04-06 21:02 UTC, YilKanda approved these changes
LGTM!

2022-04-06 21:21 UTC, merged

2022-04-07 16:18 UTC, vyk2rr commented
Great! you added the Rspec setup and tests, I have a little feedback for you:

based on this reading: https://www.betterspecs.org

------
This is the test you added: 

```ruby
escribe Employee do
  before(:each) do
    @employee = Employee.new(...
  end

  it 'is valid create with all fields values' 
  it 'Name field should have presence' 
  it 'Email field should have presence'
  it 'Position field should have presence' 
  it 'private_code field should have presence' 
  it 'Active field should have presence' 
  it 'Branch_id field should have presence' 
  it 'Email must be unique' 
  it 'Private_code must be unique' 
  it 'Private_code should have 6 characters' 
end
```

I took that and re-created that in a way that it is easier for you to read and understand:

```ruby
escribe Employee do
  before(:each) do
    @employee = Employee.new(...
  end

  it 'creates employees' 
  it "validates Employee's Name presence" 
  it "validates Employee's Email presence" 
  it "validates Employee's Position presence" 
  it "validates Employee's Private Code presence" 
  it "validates Employee's Active field presence" 
  it "validates Employee's branch_id field presence" 
  it "validates Employee's email presence" 
  it "validates Employee's email uniqueness" 
  it "validates Employee's private code uniqueness" 
  it "validates Employee's private_code with the right structure"
end
```

But even better you can take advantage of 'context' and we group tests, something more like this:

```ruby
escribe Employee do
  before(:each) do
    @employee = Employee.new(...
  end

  it 'creates employees with valid data' 
  it 'creates employees with missing data' do 
    # validates presence of: Name, Email, Position, Private Code, Active field, branch_id field

    # ^ in here you try to create an Employee with empty values
    # ^ then you look at the errors of active record:
    #     - all errors should be there for all the fields you are missing
    #     (just make sure they are there, and that's it)
  end

  it "validates Employee's email uniqueness"
  it "validates Employee's private code uniqueness"

  context 'having wrong values' do
    it "validates Employee's private_code with the right structure"
  end
end
```

I hope that it helps! :) I know this is already approved, if you read me let me know What do you think?